from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)


# ── colour palette ────────────────────────────────────────────────────────────
DARK_BLUE   = colors.HexColor('#1a3a5c')
MID_BLUE    = colors.HexColor('#2e6da4')
LIGHT_BLUE  = colors.HexColor('#dce8f5')
CONF_RED    = colors.HexColor('#c0392b')
CONF_PINK   = colors.HexColor('#fdecea')
ROW_ALT     = colors.HexColor('#f4f7fb')


def _styles():
    base = getSampleStyleSheet()
    return {
        'title': ParagraphStyle(
            'ReportTitle',
            parent=base['Title'],
            fontSize=18, textColor=DARK_BLUE, spaceAfter=4,
        ),
        'meta': ParagraphStyle(
            'Meta',
            parent=base['Normal'],
            fontSize=8, textColor=colors.grey, spaceAfter=2,
        ),
        'section': ParagraphStyle(
            'Section',
            parent=base['Heading2'],
            fontSize=12, textColor=DARK_BLUE,
            spaceBefore=14, spaceAfter=4,
            borderPad=0,
        ),
        'body': ParagraphStyle(
            'Body',
            parent=base['Normal'],
            fontSize=9, leading=13,
        ),
        'conf_header': ParagraphStyle(
            'ConfHeader',
            parent=base['Heading2'],
            fontSize=12, textColor=CONF_RED,
            spaceBefore=14, spaceAfter=4,
        ),
        'notes': ParagraphStyle(
            'Notes',
            parent=base['Normal'],
            fontSize=9, leading=13, leftIndent=6,
        ),
    }


def _kv_table(rows, col_widths=(2.0 * inch, 4.5 * inch)):
    """Render a list of (label, value) pairs as a two-column table."""
    data = [[Paragraph(f'<b>{k}</b>', _styles()['body']),
             Paragraph(str(v) if v not in (None, '') else '—', _styles()['body'])]
            for k, v in rows]
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), LIGHT_BLUE),
        ('ROWBACKGROUNDS', (1, 0), (1, -1), [colors.white, ROW_ALT]),
        ('GRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#c0cfe0')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    return t


def _section_rule(story, title, style_key='section'):
    s = _styles()
    story.append(Paragraph(title, s[style_key]))
    story.append(HRFlowable(width='100%', thickness=1,
                            color=MID_BLUE if style_key == 'section' else CONF_RED,
                            spaceAfter=6))


def _fmt_date(d):
    if d is None:
        return None
    if hasattr(d, 'strftime'):
        return d.strftime('%Y-%m-%d')
    return str(d)


class ProjectSummaryReport:
    def __init__(self, project, user, include_confidential: bool,
                 generated_by: str, generated_date: datetime, db_session=None):
        self.project = project
        self.user = user
        self.include_confidential = include_confidential
        self.generated_by = generated_by
        self.generated_date = generated_date
        self.db_session = db_session

    def build(self) -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=LETTER,
            leftMargin=0.85 * inch,
            rightMargin=0.85 * inch,
            topMargin=0.85 * inch,
            bottomMargin=0.75 * inch,
            title=f"Project Summary – {self.project.project_name}",
        )

        s = _styles()
        p = self.project
        story = []

        # ── Header ────────────────────────────────────────────────────────────
        story.append(Paragraph('Project Summary Report', s['title']))
        story.append(Paragraph(
            f'Generated by: {self.generated_by} &nbsp;|&nbsp; '
            f'Date (UTC): {self.generated_date:%Y-%m-%d %H:%M:%S}',
            s['meta']
        ))
        story.append(Spacer(1, 0.1 * inch))
        story.append(HRFlowable(width='100%', thickness=2, color=DARK_BLUE, spaceAfter=8))

        # ── Project Overview ───────────────────────────────────────────────────
        _section_rule(story, 'Project Overview')
        story.append(_kv_table([
            ('Project Name',       p.project_name),
            ('MPR Project ID',     p.mpr_project_id),
            ('Location',           p.location),
            ('Status',             p.project_status),
            ('Project Health',     p.project_health),
            ('Licensing Approach', p.licensing_approach),
            ('Configuration',      p.configuration),
            ('Project Schedule',   p.project_schedule),
            ('Target COD',         _fmt_date(p.target_cod)),
            ('COD (Commercial Op)', _fmt_date(p.cod)),
        ]))

        # ── Geographic Coordinates ─────────────────────────────────────────────
        if p.latitude is not None or p.longitude is not None:
            story.append(Spacer(1, 0.1 * inch))
            _section_rule(story, 'Geographic Coordinates')
            story.append(_kv_table([
                ('Latitude',  p.latitude),
                ('Longitude', p.longitude),
            ]))

        # ── Financial Data (Confidential) ──────────────────────────────────────
        can_see_financials = (
            self.include_confidential
            and (self.user.is_admin or getattr(self.user, 'has_confidential_access', False))
        )
        story.append(Spacer(1, 0.1 * inch))
        _section_rule(
            story,
            'Financial Data' + ('' if can_see_financials else ' [Confidential – Redacted]'),
            style_key='conf_header' if not can_see_financials else 'section'
        )
        if can_see_financials:
            capex = getattr(p, 'capex', None)
            opex  = getattr(p, 'opex',  None)
            fuel  = getattr(p, 'fuel_cost', None)
            lcoe  = getattr(p, 'lcoe',  None)
            story.append(_kv_table([
                ('CAPEX',      capex if capex not in (None, '[Confidential]') else '—'),
                ('OPEX',       opex  if opex  not in (None, '[Confidential]') else '—'),
                ('Fuel Cost',  fuel  if fuel  not in (None, '[Confidential]') else '—'),
                ('LCOE',       lcoe  if lcoe  not in (None, '[Confidential]') else '—'),
            ]))
        else:
            story.append(Paragraph(
                'Financial fields (CAPEX, OPEX, Fuel Cost, LCOE) require '
                'Confidential Access to view.',
                s['body']
            ))

        # ── Firm Involvement ───────────────────────────────────────────────────
        story.append(Spacer(1, 0.1 * inch))
        _section_rule(story, 'Firm Involvement')

        primary_contact_name = None
        last_interaction_name = None
        if self.db_session:
            from app.models import Personnel
            if p.primary_firm_contact:
                pc = self.db_session.get(Personnel, p.primary_firm_contact)
                primary_contact_name = pc.full_name if pc else None
            if p.last_project_interaction_by:
                lb = self.db_session.get(Personnel, p.last_project_interaction_by)
                last_interaction_name = lb.full_name if lb else None

        story.append(_kv_table([
            ('Firm Involvement',        p.firm_involvement),
            ('Primary Firm Contact',    primary_contact_name or (
                f'ID {p.primary_firm_contact}' if p.primary_firm_contact else None)),
            ('Last Interaction Date',   _fmt_date(p.last_project_interaction_date)),
            ('Last Interaction By',     last_interaction_name or (
                f'ID {p.last_project_interaction_by}' if p.last_project_interaction_by else None)),
        ]))

        # ── Company Roles ──────────────────────────────────────────────────────
        if self.db_session:
            from app.models.company import CompanyRoleAssignment, CompanyRole, Company
            from sqlalchemy.orm import joinedload

            assignments = (
                self.db_session.query(CompanyRoleAssignment)
                .filter_by(context_type='Project', context_id=p.project_id)
                .options(
                    joinedload(CompanyRoleAssignment.company),
                    joinedload(CompanyRoleAssignment.role),
                )
                .order_by(CompanyRoleAssignment.is_primary.desc())
                .all()
            )

            if assignments:
                story.append(Spacer(1, 0.1 * inch))
                _section_rule(story, 'Company Roles')

                # Group by role label
                from collections import defaultdict
                by_role = defaultdict(list)
                for a in assignments:
                    label = a.role.role_label if a.role else 'Unknown'
                    by_role[label].append(a)

                for role_label, items in sorted(by_role.items()):
                    story.append(Paragraph(f'<b>{role_label}</b>', s['body']))
                    rows = []
                    for a in items:
                        name = a.company.company_name if a.company else '—'
                        flags = []
                        if a.is_primary:
                            flags.append('Primary')
                        if a.start_date or a.end_date:
                            date_str = ' to '.join(filter(None, [
                                _fmt_date(a.start_date), _fmt_date(a.end_date)
                            ]))
                            flags.append(date_str)
                        detail = ' | '.join(flags) if flags else ''
                        rows.append([name, detail, a.notes or ''])

                    col_w = [2.5 * inch, 1.8 * inch, 2.2 * inch]
                    header_row = [
                        Paragraph('<b>Company</b>', s['body']),
                        Paragraph('<b>Notes</b>', s['body']),
                        Paragraph('<b>Details</b>', s['body']),
                    ]
                    tdata = [header_row] + [
                        [Paragraph(r[0], s['body']),
                         Paragraph(r[1], s['body']),
                         Paragraph(r[2], s['body'])]
                        for r in rows
                    ]
                    t = Table(tdata, colWidths=col_w)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), MID_BLUE),
                        ('TEXTCOLOR',  (0, 0), (-1, 0), colors.white),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ROW_ALT]),
                        ('GRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#c0cfe0')),
                        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ('TOPPADDING', (0, 0), (-1, -1), 4),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                        ('LEFTPADDING', (0, 0), (-1, -1), 6),
                        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 0.08 * inch))

        # ── Notes ──────────────────────────────────────────────────────────────
        if p.notes:
            story.append(Spacer(1, 0.1 * inch))
            _section_rule(story, 'Notes')
            story.append(Paragraph(p.notes.replace('\n', '<br/>'), s['notes']))

        doc.build(story)
        data = buffer.getvalue()
        buffer.close()
        return data
